### ISSUE TITLE
 WikiTables-WithLinks error

### ISSUE THREAD

**Issue by xhjcxxl** [wenhuchen/WikiTables-WithLinks#2]
some table id are different in the  WikiTables-WithLinks and train.json, such as：WikiTables-WithLinks have double subline，then use train.json's table id cant find it, train.json's table id don't have double subline: ‘__’

**Comment by wenhuchen** [comment]
1. I can't find any table in tables_tok with "__" by running command:
```
ls tables_tok/*.json | grep "__" | less
```
2. the train.json only comprises a subset  (~11K) of all the tables in the tables_tok/, request_tok/ because some of the questions are filtered out in the data annotation due to bad quality.
